"""Feed-forward thruster current model + a summed-current budget scaler.

This module predicts how much current the thrusters will draw from the
*commanded* normalized thrust and the supply voltage, using the official
BlueRobotics T200 performance data (bundled as ``t200_current_model.json``,
generated by ``tools/build_t200_current_model.py``).

Why this exists
---------------
The MATE Ranger rules cap the vehicle behind a 25 A fuse. A single T200 at full
throttle pulls ~17 A at 12 V and ~20 A at 14 V, so commanding several thrusters
hard at once trivially exceeds 25 A and pops the fuse. None of the existing
limiters look at the *summed* current across all thrusters -- ``global_limit``
only caps the single largest thruster. This module closes that gap.

It is purely *feed-forward*: it needs no current sensor, so it is unaffected by
the (currently untrusted) Power Sense Module. The control loop knows exactly
what PWM it is about to command, so it can predict the draw and scale every
thruster down by a single shared factor when the predicted total would exceed
the budget -- preserving the pilot's intended direction/shape, exactly like
``global_limit`` does for peak thrust but for total current.

Everything here is pure Python (no numpy) and side-effect free so it can be
called from the hot control loop and is trivially unit-testable.
"""

from __future__ import annotations

import bisect
import json
import os
from typing import Dict, List, Mapping, Tuple


def _clamp(x: float, lo: float, hi: float) -> float:
    return lo if x < lo else hi if x > hi else x


def _interp(xs: List[float], ys: List[float], x: float) -> float:
    """Linear interpolation on ascending ``xs`` with flat extrapolation."""
    if not xs:
        return 0.0
    if x <= xs[0]:
        return ys[0]
    if x >= xs[-1]:
        return ys[-1]
    i = bisect.bisect_right(xs, x)
    x0, x1 = xs[i - 1], xs[i]
    y0, y1 = ys[i - 1], ys[i]
    if x1 == x0:
        return y0
    t = (x - x0) / (x1 - x0)
    return y0 + t * (y1 - y0)


class T200CurrentModel:
    """Predict per-thruster current draw (A) from normalized command + voltage.

    The normalized command convention matches the control loop: ``-1`` is full
    reverse, ``0`` neutral (~0 A), ``+1`` full forward. It is mapped onto the
    data's PWM grid (1100..1900 us, neutral 1500) before lookup.
    """

    def __init__(self, voltages: List[float], pwm_grids: List[List[float]], current_grids: List[List[float]], *, neutral_us: float = 1500.0):
        if not voltages:
            raise ValueError("T200CurrentModel requires at least one voltage curve")
        order = sorted(range(len(voltages)), key=lambda i: voltages[i])
        self.voltages: List[float] = [float(voltages[i]) for i in order]
        self._pwm: List[List[float]] = [[float(p) for p in pwm_grids[i]] for i in order]
        self._cur: List[List[float]] = [[abs(float(c)) for c in current_grids[i]] for i in order]
        self.neutral_us = float(neutral_us)
        # Symmetric half-span derived from the data so norm->pwm matches the grid.
        half_spans = []
        for grid in self._pwm:
            if grid:
                half_spans.append(min(self.neutral_us - grid[0], grid[-1] - self.neutral_us))
        self.half_span_us = min(half_spans) if half_spans else 400.0
        if self.half_span_us <= 0:
            self.half_span_us = 400.0

    # ---- construction -------------------------------------------------
    @classmethod
    def from_payload(cls, payload: Mapping) -> "T200CurrentModel":
        curves = list(payload.get("curves") or [])
        if not curves:
            raise ValueError("current model payload has no curves")
        volts = [float(c["voltage"]) for c in curves]
        pwm = [[float(x) for x in c["pwm_us"]] for c in curves]
        cur = [[float(x) for x in c["current_a"]] for c in curves]
        neutral = float((payload.get("meta") or {}).get("pwm_neutral_us", 1500))
        return cls(volts, pwm, cur, neutral_us=neutral)

    @classmethod
    def from_json(cls, path: str) -> "T200CurrentModel":
        with open(path, "r", encoding="utf-8") as f:
            return cls.from_payload(json.load(f))

    @classmethod
    def bundled(cls) -> "T200CurrentModel":
        """Load the JSON shipped next to this module."""
        path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "t200_current_model.json")
        return cls.from_json(path)

    # ---- lookup -------------------------------------------------------
    def _pwm_for_norm(self, norm: float) -> float:
        return self.neutral_us + self.half_span_us * _clamp(float(norm), -1.0, 1.0)

    def current_for_norm(self, norm: float, voltage: float) -> float:
        """Predicted current draw (A) for one thruster at ``norm`` and ``voltage``."""
        pwm = self._pwm_for_norm(norm)
        v = _clamp(float(voltage), self.voltages[0], self.voltages[-1])

        # Current within each bracketing voltage curve, then interpolate by voltage.
        j = bisect.bisect_right(self.voltages, v)
        if j <= 0:
            return _interp(self._pwm[0], self._cur[0], pwm)
        if j >= len(self.voltages):
            return _interp(self._pwm[-1], self._cur[-1], pwm)
        v0, v1 = self.voltages[j - 1], self.voltages[j]
        c0 = _interp(self._pwm[j - 1], self._cur[j - 1], pwm)
        c1 = _interp(self._pwm[j], self._cur[j], pwm)
        if v1 == v0:
            return c0
        t = (v - v0) / (v1 - v0)
        return c0 + t * (c1 - c0)

    def total_current(self, norms: Mapping[str, float], voltage: float) -> float:
        """Sum of predicted current across the given thruster commands (A)."""
        return sum(self.current_for_norm(float(n), voltage) for n in norms.values())


def current_budget_scale(
    norms: Mapping[str, float],
    model: T200CurrentModel,
    *,
    voltage: float,
    budget_a: float,
    min_scale: float = 0.0,
    extra_load_a: float = 0.0,
    max_iter: int = 40,
) -> Tuple[float, float, float]:
    """Largest shared scale in ``[min_scale, 1]`` keeping predicted total <= budget.

    ``extra_load_a`` is additional current draw that is *not* scaled here -- e.g.
    the back-gripper / wrist T200, which is a manipulation-priority load on the
    same fuse. It is reserved off the top of the budget so the scalable
    propulsion thrusters yield to it (rather than the gripper weakening). The
    returned totals INCLUDE ``extra_load_a`` so the topside readout reflects the
    full predicted draw the fuse actually sees.

    Returns ``(scale, predicted_before_a, predicted_after_a)``. Because each
    thruster's current is monotonic in ``|command|`` and scaling moves every
    command toward neutral, the predicted total is monotonic in the scale, so a
    bisection converges cleanly. ``scale == 1.0`` means the budget was not
    binding (no change).
    """
    min_scale = _clamp(float(min_scale), 0.0, 1.0)
    budget_a = max(0.0, float(budget_a))
    extra = max(0.0, float(extra_load_a))

    def total(s: float) -> float:
        return sum(model.current_for_norm(s * float(n), voltage) for n in norms.values())

    base = total(1.0)
    before = base + extra
    # Budget left for the scalable thrusters after the fixed (priority) load.
    thr_budget = budget_a - extra
    if base <= thr_budget or base <= 0.0:
        return 1.0, before, before

    floor_total = total(min_scale)
    if thr_budget <= 0.0 or floor_total >= thr_budget:
        # The fixed load alone meets/exceeds budget, or even the thruster floor
        # does; clamp thrusters to the floor (best we can do) and report it.
        return min_scale, before, floor_total + extra

    lo, hi = min_scale, 1.0
    for _ in range(int(max_iter)):
        mid = 0.5 * (lo + hi)
        if total(mid) > thr_budget:
            hi = mid
        else:
            lo = mid
    return lo, before, total(lo) + extra
